from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator


class LoginRequest(BaseModel):
    """Pydantic contract for a login request.

    The email and password must be non‑empty strings. Validation errors are raised by Pydantic.
    """

    email: str = Field(..., description="User e‑mail address")
    password: str = Field(..., description="User password")

    @field_validator("email")
    def email_valid(cls, v: str) -> str:
        if not v:
            raise ValueError("email must not be empty")
        if "@" not in v:
            raise ValueError("email must contain '@'")
        return v

    @field_validator("password")
    def password_not_empty(cls, v: str) -> str:
        if not v:
            raise ValueError("password must not be empty")
        return v


class LoginResponse(BaseModel):
    """Pydantic contract for a login response.

    ``access_token`` contains an opaque token generated by the service. ``token_type`` is
    always the literal string ``bearer``.
    """

    access_token: str = Field(..., description="Opaque access token")
    token_type: Literal["bearer"] = "bearer"


class User(BaseModel):
    """Domain model representing a user.

    ``email`` is stored lower‑case for case‑insensitive look‑ups. ``password_hash`` holds a
    hashed password. ``is_active`` indicates if the user may authenticate.
    """

    email: str = Field(..., description="User e‑mail address")
    password_hash: str = Field(..., description="SHA‑256 hash of the password")
    is_active: bool = Field(True, description="Whether the user is active")

    @field_validator("email")
    def normalize_email(cls, v: str) -> str:
        return v.lower()

    model_config = ConfigDict(from_attributes=True)
